import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/src/components/navbar";
import Transitionpages from "@/src/components/trasnsitionpages";

export const metadata = {
  title: "Suresh Kumavat",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="">

        <Transitionpages>{children}</Transitionpages>

      </body>
    </html>
  );
}
